import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      {
        extends: "./vitest.projects.node.ts",
        test: {
          name: "node",
          include: [
            "packages/core/**/*.test.ts",
            "packages/assets/**/*.test.ts",
            "packages/edit/**/*.test.ts",
            "packages/object-model/**/*.test.ts",
            "packages/physics/**/*.test.ts",
            "packages/bridge/**/*.test.ts",
            "packages/runtime/**/*.test.ts",
            "packages/debugger/**/*.test.ts",
            "packages/ui-runtime/**/*.test.ts",
            "packages/anim-graph/**/*.test.ts",
            "packages/shader-graph/**/*.test.ts",
            "packages/input/**/*.test.ts",
            "packages/ui/**/*.test.ts",
            "packages/scripting/**/*.test.ts",
            "packages/scripting-nodes/**/*.test.ts",
            "packages/test-kit/**/*.test.ts",
            "apps/docs/**/*.test.ts",
            "playwright.config.test.ts",
          ],
        },
      },
      {
        extends: "./vitest.projects.jsdom.ts",
        test: {
          name: "jsdom",
          include: [
            "packages/editor-kit/**/*.test.tsx",
            "packages/graph-ui/**/*.test.{ts,tsx}",
            "packages/vfs/**/*.test.ts",
            "apps/editor/**/*.test.{ts,tsx}",
          ],
        },
      },
      {
        extends: "./vitest.projects.babylon.ts",
        test: {
          name: "babylon",
          include: ["packages/render/**/*.test.ts"],
        },
      },
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      // Packages carry unit-coverage gates; apps/editor is covered by e2e.
      include: ["packages/*/src/**/*.{ts,tsx}"],
      exclude: [
        // Capacitor-backed composites need a device; covered by P1 device spikes.
        "**/mobile-storage-adapter.ts",
        "**/preferences-app-settings.ts",
        // Documents adapter production path uses Capacitor Filesystem; behaviour
        // is covered by documents-adapter.test.ts with an injected fake FS.
        "**/documents-adapter.ts",
        // Thin factory over OPFS/Documents; covered by Playwright cold-reopen.
        "**/derived-storage.ts",
        // Node adapter is CI/tooling-only; covered by its own unit tests without
        // dragging the browser package coverage gate.
        "**/node-adapter.ts",
        // Needs a real WebGL context; covered by the Playwright viewport specs.
        "**/create-engine.ts",
        // Standalone CreateFullscreenUI + Canvas2D blit; covered by Playwright HUD / designer.
        "**/ui-surface.ts",
        // Game worker entry needs a Worker host; covered by Play e2e.
        "**/worker-entry.ts",
        // Physics wasm backends: HavokPlugin path is asserted in havok-v2.test.ts;
        // coverage of the Babylon/Havok wasm surface is environment-dependent.
        "**/havok-backend.ts",
        "**/havok-loader.ts",
        "**/rapier-backend.ts",
        // Browser Worker + OffscreenCanvas encode path; covered by editor wiring
        // and the Node Basis A16 smoke (`node-basis-encode.ts`).
        "**/worker-encode.ts",
        "**/decode-source-rgba.ts",
        // shadcn primitives are generated by the CLI, not authored here.
        "packages/ui/**",
        "**/index.ts",
        "**/styles/**",
        "**/test-support/**",
      ],
      thresholds: {
        "packages/core/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/editor-kit/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/graph-ui/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/render/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/test-kit/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/assets/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/edit/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/object-model/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/physics/src/**": {
          lines: 50,
          functions: 50,
          branches: 45,
          statements: 50,
        },
        "packages/bridge/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/runtime/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/debugger/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/ui-runtime/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/anim-graph/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/shader-graph/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/input/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/scripting/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/scripting-nodes/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/vfs/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
      },
    },
  },
});
