import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    projects: [
      {
        extends: "./vitest.projects.node.ts",
        test: {
          name: "node",
          include: [
            "packages/core/**/*.test.ts",
            "packages/assets/**/*.test.ts",
            "packages/test-kit/**/*.test.ts",
          ],
        },
      },
      {
        extends: "./vitest.projects.jsdom.ts",
        test: {
          name: "jsdom",
          include: [
            "packages/editor-kit/**/*.test.tsx",
            "packages/graph-ui/**/*.test.{ts,tsx}",
            "packages/vfs/**/*.test.ts",
            "apps/editor/**/*.test.ts",
          ],
        },
      },
      {
        extends: "./vitest.projects.babylon.ts",
        test: {
          name: "babylon",
          include: ["packages/render/**/*.test.ts"],
        },
      },
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      // Packages carry unit-coverage gates; apps/editor is covered by e2e.
      include: ["packages/*/src/**/*.{ts,tsx}"],
      exclude: [
        // Capacitor-backed adapters need a device; covered by P1 device spikes.
        "**/scoped-storage-adapter.ts",
        "**/mobile-storage-adapter.ts",
        "**/preferences-app-settings.ts",
        // Node adapter is CI/tooling-only; covered by its own unit tests without
        // dragging the browser package coverage gate.
        "**/node-adapter.ts",
        // Needs a real WebGL context; covered by the Playwright viewport specs.
        "**/create-engine.ts",
        // shadcn primitives are generated by the CLI, not authored here.
        "packages/ui/**",
        "**/index.ts",
        "**/styles/**",
        "**/test-support/**",
      ],
      thresholds: {
        "packages/core/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/editor-kit/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/graph-ui/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/render/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/test-kit/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/assets/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
        "packages/vfs/src/**": {
          lines: 60,
          functions: 60,
          branches: 60,
          statements: 60,
        },
      },
    },
  },
});
