/** Tests with a real DOM dependency, including transitive browser services. */
export const domLogicTests = [
  "apps/editor/src/lib/audio-preview.test.ts",
  "apps/editor/src/services/template-service.test.ts",
  "apps/editor/src/services/project-service.test.ts",
  "apps/editor/src/services/project-service.assets.test.ts",
  "apps/editor/src/services/lifecycle-pause.test.ts",
  "apps/editor/src/services/edit-gesture-boundaries.test.ts",
  "apps/editor/src/services/input-capture.test.ts",
  "apps/editor/src/lib/content-browser-helpers.test.ts",
  "apps/editor/src/lib/play-preview-aspect.test.ts",
  "apps/editor/src/lib/project-engine.test.ts",
  "apps/editor/src/lib/resolved-theme.test.ts",
  "apps/editor/src/lib/viewport-render-gate.test.ts",
  "packages/graph-ui/src/graph-connect.test.ts",
  "packages/graph-ui/src/graph-marquee.test.ts",
  "packages/graph-ui/src/graph-canvas-api.test.ts",
  "packages/vfs/src/web-adapter.test.ts",
  "packages/vfs/src/test-mode.test.ts",
  "packages/vfs/src/template-storage.test.ts",
  "packages/vfs/src/capacitor-audio-lifecycle.test.ts",
  "packages/vfs/src/capacitor-app-lifecycle.test.ts",
  "packages/vfs/src/app-settings.test.ts",
  "packages/vfs/src/import-picker.test.ts",
];
