import {
  pin,
  type NodeDefinition,
  FLOAT,
  INT,
  BOOL,
} from "@babylonslate/scripting";
import { ARITHMETIC_SEARCH_ALIASES } from "./arithmetic-search-aliases";

function binary(
  id: string,
  title: string,
  op: string,
  type: typeof FLOAT | typeof INT = FLOAT,
): NodeDefinition {
  return {
    id,
    title,
    category: "math",
    searchAliases: ARITHMETIC_SEARCH_ALIASES[op],
    pure: true,
    pins: () => [
      pin("a", "a", "in", type),
      pin("b", "b", "in", type),
      pin("out", "out", "out", type),
    ],
    codegen: (ctx) => ({
      out: `(${ctx.input("a")} ${op} ${ctx.input("b")})`,
    }),
  };
}

export const mathNodes: NodeDefinition[] = [
  binary("math.add", "Add", "+"),
  binary("math.sub", "Subtract", "-"),
  binary("math.mul", "Multiply", "*"),
  binary("math.div", "Divide", "/"),
  binary("math.mod", "Modulo", "%"),
  binary("math.add_int", "Add Int", "+", INT),
  binary("math.sub_int", "Subtract Int", "-", INT),
  binary("math.mul_int", "Multiply Int", "*", INT),
  binary("math.div_int", "Divide Int", "/", INT),
  binary("math.mod_int", "Modulo Int", "%", INT),
  {
    id: "math.negate",
    searchAliases: ["-","−","-x","negation"],
    title: "Negate",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "in", "in", FLOAT),
      pin("out", "out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `(-(${ctx.input("in")}))` }),
  },
  {
    id: "math.abs",
    searchAliases: ["abs","abs(x)","|x|"],
    title: "Abs",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "in", "in", FLOAT),
      pin("out", "out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.abs(${ctx.input("in")})` }),
  },
  {
    id: "math.compare",
    searchAliases: ["≈","~=","approximately equal"],
    title: "Nearly Equal",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", FLOAT),
      pin("b", "b", "in", FLOAT),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `(Math.abs((${ctx.input("a")}) - (${ctx.input("b")})) < 1e-6)`,
    }),
  },
  {
    id: "math.equals",
    searchAliases: ["=","==","===","a == b"],
    title: "Equal",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "A", "in", FLOAT),
      pin("b", "B", "in", FLOAT),
      pin("out", "Out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) === (${ctx.input("b")}))`,
    }),
  },
  {
    id: "math.notEquals",
    searchAliases: ["!=","!==","≠","a != b"],
    title: "Not Equal",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "A", "in", FLOAT),
      pin("b", "B", "in", FLOAT),
      pin("out", "Out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) !== (${ctx.input("b")}))`,
    }),
  },
  {
    id: "math.greater",
    searchAliases: [">","a > b"],
    title: "Greater Than",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", FLOAT),
      pin("b", "b", "in", FLOAT),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({ out: `((${ctx.input("a")}) > (${ctx.input("b")}))` }),
  },
  {
    id: "math.greaterEqual",
    searchAliases: [">=","≥","a >= b"],
    title: "Greater or Equal",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", FLOAT),
      pin("b", "b", "in", FLOAT),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) >= (${ctx.input("b")}))`,
    }),
  },
  {
    id: "math.less",
    searchAliases: ["<","a < b"],
    title: "Less Than",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", FLOAT),
      pin("b", "b", "in", FLOAT),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({ out: `((${ctx.input("a")}) < (${ctx.input("b")}))` }),
  },
  {
    id: "math.lessEqual",
    searchAliases: ["<=","≤","a <= b"],
    title: "Less or Equal",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", FLOAT),
      pin("b", "b", "in", FLOAT),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) <= (${ctx.input("b")}))`,
    }),
  },
  {
    id: "boolean.and",
    searchAliases: ["&&","∧","a && b"],
    title: "Boolean And",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", BOOL),
      pin("b", "b", "in", BOOL),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) && (${ctx.input("b")}))`,
    }),
  },
  {
    id: "boolean.or",
    searchAliases: ["||","∨","a || b"],
    title: "Boolean Or",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "a", "in", BOOL),
      pin("b", "b", "in", BOOL),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) || (${ctx.input("b")}))`,
    }),
  },
  {
    id: "boolean.not",
    searchAliases: ["!","¬","!x"],
    title: "Boolean Not",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "in", "in", BOOL),
      pin("out", "out", "out", BOOL),
    ],
    codegen: (ctx) => ({ out: `!(${ctx.input("in")})` }),
  },
  {
    id: "math.lerp",
    searchAliases: ["lerp","mix(a,b,t)","lerp(a,b,t)","a+(b-a)*t"],
    title: "Lerp",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "A", "in", FLOAT),
      pin("b", "B", "in", FLOAT),
      pin("alpha", "Alpha", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("a")}) + ((${ctx.input("b")}) - (${ctx.input("a")})) * (${ctx.input("alpha")}))`,
    }),
  },
  {
    id: "math.clamp",
    searchAliases: ["clamp(x,min,max)"],
    title: "Clamp",
    category: "math",
    pure: true,
    pins: () => [
      pin("value", "Value", "in", FLOAT),
      pin("min", "Min", "in", FLOAT),
      pin("max", "Max", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `Math.min((${ctx.input("max")}), Math.max((${ctx.input("min")}), (${ctx.input("value")})))`,
    }),
  },
  {
    id: "math.min",
    searchAliases: ["min","min(a,b)"],
    title: "Min",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "A", "in", FLOAT),
      pin("b", "B", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `Math.min((${ctx.input("a")}), (${ctx.input("b")}))`,
    }),
  },
  {
    id: "math.max",
    searchAliases: ["max","max(a,b)"],
    title: "Max",
    category: "math",
    pure: true,
    pins: () => [
      pin("a", "A", "in", FLOAT),
      pin("b", "B", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `Math.max((${ctx.input("a")}), (${ctx.input("b")}))`,
    }),
  },
  {
    id: "math.sin",
    searchAliases: ["sin","sin(x)"],
    title: "Sin",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.sin(${ctx.input("in")})` }),
  },
  {
    id: "math.cos",
    searchAliases: ["cos","cos(x)"],
    title: "Cos",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.cos(${ctx.input("in")})` }),
  },
  {
    id: "math.degrees",
    searchAliases: ["degrees(x)","rad2deg","x * 180 / pi"],
    title: "Radians To Degrees",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("in")}) * 180 / Math.PI)`,
    }),
  },
  {
    id: "math.radians",
    searchAliases: ["radians(x)","deg2rad","x * pi / 180"],
    title: "Degrees To Radians",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `((${ctx.input("in")}) * Math.PI / 180)`,
    }),
  },
  {
    id: "math.floor",
    searchAliases: ["floor(x)","⌊x⌋"],
    title: "Floor",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.floor(${ctx.input("in")})` }),
  },
  {
    id: "math.ceil",
    searchAliases: ["ceil","ceil(x)","⌈x⌉"],
    title: "Ceil",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.ceil(${ctx.input("in")})` }),
  },
  {
    id: "math.round",
    searchAliases: ["round(x)"],
    title: "Round",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.round(${ctx.input("in")})` }),
  },
  {
    id: "math.sign",
    searchAliases: ["sign(x)","sgn"],
    title: "Sign",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.sign(${ctx.input("in")})` }),
  },
  {
    id: "math.power",
    searchAliases: ["^","**","pow","pow(a,b)","a^b","a**b"],
    title: "Power",
    category: "math",
    pure: true,
    pins: () => [
      pin("base", "Base", "in", FLOAT),
      pin("exp", "Exp", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({
      out: `Math.pow((${ctx.input("base")}), (${ctx.input("exp")}))`,
    }),
  },
  {
    id: "math.sqrt",
    searchAliases: ["√","sqrt","sqrt(x)","√x"],
    title: "Sqrt",
    category: "math",
    pure: true,
    pins: () => [
      pin("in", "In", "in", FLOAT),
      pin("out", "Out", "out", FLOAT),
    ],
    codegen: (ctx) => ({ out: `Math.sqrt(${ctx.input("in")})` }),
  },
  {
    id: "math.random",
    title: "Random Float",
    category: "math",
    pure: true,
    pins: () => [pin("out", "Out", "out", FLOAT)],
    codegen: () => ({ out: `ctx.random.float()` }),
  },
  {
    id: "math.randomInt",
    title: "Random Int",
    category: "math",
    pure: true,
    pins: () => [
      pin("min", "Min", "in", INT),
      pin("max", "Max", "in", INT),
      pin("out", "Out", "out", INT),
    ],
    codegen: (ctx) => ({
      out: `ctx.random.int((${ctx.input("min")}) | 0, (${ctx.input("max")}) | 0)`,
    }),
  },
  {
    id: "math.randomBool",
    title: "Random Bool",
    category: "math",
    pure: true,
    pins: () => [pin("out", "Out", "out", BOOL)],
    codegen: () => ({ out: `ctx.random.bool()` }),
  },
];
