import { expect, test } from "@playwright/test";
import { openMinimalTestProject } from "./minimal-project";
import { openMainScene } from "./open-test-project";

test("viewport shortcuts match menu hints and closing preserves the dirty document prompt", async ({ page }, testInfo) => {
  await openMinimalTestProject(page);
  await openMainScene(page);
  await page.getByTestId("gizmo-snap-toggle").focus();
  const before = await page.getByTestId("gizmo-snap-toggle").getAttribute("aria-pressed");
  await page.keyboard.press("g");
  await expect(page.getByTestId("gizmo-snap-toggle")).toHaveAttribute("aria-pressed", before === "true" ? "false" : "true");
  await page.getByTestId("viewport-settings").click();
  const grid = page.getByTestId("viewport-show-grid-toggle");
  await expect(grid).toHaveAttribute("aria-keyshortcuts", "Shift+G");
  await expect(grid.locator("kbd").last()).toBeVisible();
  const gridBefore = await grid.getAttribute("aria-checked");
  await page.screenshot({ path: testInfo.outputPath("viewport-shortcut-hints.png"), animations: "disabled" });
  await page.keyboard.press("Escape");
  await expect(page.getByTestId("viewport-settings-menu")).toBeHidden();
  await expect(page.getByTestId("viewport-settings")).toBeFocused();
  await page.keyboard.press("Shift+g");
  await page.getByTestId("viewport-settings").click();
  await expect(grid).toHaveAttribute("aria-checked", gridBefore === "true" ? "false" : "true");
  await page.keyboard.press("Escape");
  await expect(page.getByTestId("viewport-settings-menu")).toBeHidden();
  await expect(page.getByTestId("viewport-settings")).toBeFocused();
  await page.keyboard.press("Alt+w");
  await expect(page.getByTestId("dirty-close-dialog")).toBeVisible();
  await page.getByTestId("dirty-cancel").click();
  await expect(page.getByTestId("dirty-close-dialog")).toHaveCount(0);
  await expect(page.getByTestId("viewport-canvas")).toBeVisible();
  await page.keyboard.press("Alt+b");
  await expect(page.getByTestId("content-browser-workspace")).toBeVisible();
  await page.keyboard.press("Alt+PageDown");
  await expect(page.getByTestId("viewport-canvas")).toBeVisible();
  await page.getByTestId("outliner-add-folder").focus();
  await page.keyboard.press("ControlOrMeta+f");
  await expect(page.getByTestId("outliner-search")).toBeFocused();
  await page.getByTestId("outliner-add-actor").focus();
  await page.keyboard.press("Alt+a");
  await expect(page.getByTestId("place-actors-catalog")).toBeVisible();
  await page.getByTestId("place-actors-item-shape-box").click();
  await expect(page.getByTestId("place-actors-catalog")).toHaveCount(0);
  await expect(page.getByTestId("scene-outliner-panel").getByRole("treeitem", { name: "box", exact: true })).toBeVisible();
});
