export {
  MATERIAL_CATALOG,
  materialNodeDefinition,
  materialPaletteEntries,
  nodeIsLegalInDomain,
  nodeIsLegalInStage,
  terminalNodeTypeFor,
  type MaterialCapability,
  type MaterialDomain,
  type MaterialNodeDefinition,
  type MaterialPinDefinition,
  type MaterialPinType,
  type MaterialStage,
} from "./catalog";
export {
  MATERIAL_FUNCTION_SCHEMA_VERSION,
  MATERIAL_PREVIEW_MESHES,
  MATERIAL_SCHEMA_VERSION,
  createDefaultMaterialDocument,
  createDefaultMaterialFunctionDocument,
  materialDependencies,
  migrateLegacyShaderPayload,
  normalizeMaterialDocument,
  normalizeMaterialFunctionDocument,
  setMaterialDomain,
  type LegacyShaderMigrationContext,
  type MaterialBlendMode,
  type MaterialDependencies,
  type MaterialDocument,
  type MaterialFunctionDocument,
  type MaterialFunctionPin,
  type MaterialGraphEdge,
  type MaterialGraphNode,
  type MaterialPreviewMesh,
  type MaterialPreviewSettings,
  type MaterialShadingModel,
} from "./document";
export {
  lowerMaterialDocument,
  materialCompileKey,
  type MaterialBuildPlan,
  type MaterialBufferRequirements,
  type MaterialCostFeatures,
  type MaterialLowerContext,
  type MaterialLowerResult,
  type MaterialOperand,
  type MaterialOperation,
  type MaterialOperationSource,
  type MaterialTextureBinding,
} from "./lower";
export { createTypeResolver, type TypeResolver } from "./resolve";
export {
  hydrateMaterialGraphForEditor,
  materialGraphToSerialized,
  materialPaletteNodes,
  materialPinTypeIsNumeric,
  materialPinsAreCompatible,
  pinsForMaterialNode,
  serializedToMaterialFunctionGraph,
  serializedToMaterialGraph,
  type MaterialGraphPin,
  type MaterialPaletteNode,
  type MaterialPinContext,
} from "./serialize-material";
export {
  asNumberArray,
  listUnconnectedMaterialPinDefaults,
  materialPinDefaultPropertyKey,
  readMaterialPinDefault,
  resolveMaterialPinDefault,
  type MaterialPinDefault,
  type MaterialPinDefaultContext,
} from "./pin-defaults";
export {
  componentCount,
  conversionFor,
  isNumericType,
  materialTypeLabel,
  resolveGenericType,
  typesAreAssignable,
  MATERIAL_NUMERIC_TYPES,
  type MaterialConversion,
  type MaterialValueType,
} from "./types";
export {
  collectFunctionDependencies,
  customGlslBody,
  findGraphCycle,
  validateCustomGlslBody,
  validateMaterialDocument,
  validateMaterialFunctionDocument,
  type MaterialCapabilities,
  type MaterialDiagnostic,
  type MaterialDiagnosticSeverity,
  type MaterialValidationContext,
} from "./validate";
export {
  classifyMaterialCost,
  materialPreviewReducer,
  createMaterialPreviewState,
  renderActionEnabled,
  shouldAutoCompile,
  type MaterialCostClass,
  type MaterialPreviewEvent,
  type MaterialPreviewPolicy,
  type MaterialPreviewState,
  type MaterialPreviewStatus,
} from "./preview-state";
